### ISSUE TITLE
new_caption_train.json、new_caption_test.json文件缺少

### ISSUE THREAD

**Issue by ggg0919** [YangBin55/DDCOT#1]
您好，请问一下，data/scienceqa/new_caption_train.json和data/scienceqa/new_caption_test.json这两个文件是您们自己生成的吗，在原始的scienceqa数据集中没有这两个文件，可以上传一下嘛

**Comment by YangBin55** [comment]
我们已经将这两个文件上传到了云盘[Google Drive](https://drive.google.com/drive/folders/1BeipodkLa7rH5QIodF3B_Xda1MCZrq9Y?usp=drive_link)。感谢您对我们工作的关注！
