### ISSUE TITLE
reform_Rv2_train_noR.json, new_R.json

### ISSUE THREAD

**Issue by yeonju7kim** [YangBin55/DDCOT#2]
Hi, Thank you for your wonderful work.

I want to run this code, but I don't know where the below files are.
reform_Rv2_train_noR.json, new_R.json

https://github.com/SooLab/DDCOT/blob/5f403372d1a8f0ab4ad785c2674fa64b71a1e2fe/utils_data.py#L245

**Comment by YangBin55** [comment]
> Hi, Thank you for your wonderful work.
> 
> I want to run this code, but I don't know where the below files are. reform_Rv2_train_noR.json, new_R.json
> 
> https://github.com/SooLab/DDCOT/blob/5f403372d1a8f0ab4ad785c2674fa64b71a1e2fe/utils_data.py#L245

Sorry for the mistakes in file names. We have updated the utils_data.py and fix these typos.
