### ISSUE TITLE
Which format of prompt did you use? QCMG-A or? 

### ISSUE THREAD

**Issue by TongLiu-github** [YangBin55/DDCOT#3]
In https://github.com/SooLab/DDCOT/blob/master/utils_prompt.py, there are many formats of input and output, which one did you use to generate the results in Table 1?

**Comment by YangBin55** [comment]
Yes, we use the QCMG-A format

**Comment by zhangbaijin** [comment]
It's great work, now i am following your work, can we add wechat? my wechat:SemiZxf
