### ISSUE TITLE
The size of tensor a (512) must match the size of tensor b (534) at non-singleton dimension 3

### ISSUE THREAD

**Issue by 0x4e8** [YangBin55/DDCOT#4]
Thank you for your contribution. I am a newbie in nlp. When I ran the Train command, I got the error "RuntimeError: The size of tensor a (512) must match the size of tensor b (534) at non-singleton dimension 3". Please tell me How to solve it?
![1](https://github.com/SooLab/DDCOT/assets/116562172/24805eb3-1516-4f1e-8ee6-63bc1b3c9a56)
![2](https://github.com/SooLab/DDCOT/assets/116562172/6aca73e5-5839-41ca-8735-500707297dae)
![3](https://github.com/SooLab/DDCOT/assets/116562172/1ba7a95d-5a4c-4190-bb5b-b868f8eaca3f)

**Comment by YangBin55** [comment]
Hi ,
Thank you for your interest in the project.
We modified some code in the transformer library to fit our network architecture and placed our modified code in the transformer folder. Please verify the correct usage of the called functions.
Thanks again for your collaboration.
Best regards, 
YangBin

**Comment by 0x4e8** [comment]
Based on your reply, I have solved the problem. Thank you.


Best regards,
Zeng
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SooLab/DDCOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SooLab/DDCOT] The size of tensor a (512) must match the size of tensor b (534) at non-singleton dimension 3 (Issue #4)





 
Hi ,
 Thank you for your interest in the project.
 We modified some code in the transformer library to fit our network architecture and placed our modified code in the transformer folder. Please verify the correct usage of the called functions.
 Thanks again for your collaboration.
 Best regards,
 YangBin

**Comment by 0x4e8** [comment]
According to your reply, I have already solved this problem. Thank you.


Additionally, I have another question. Could you please tell me about the device and time it took to train the model?



Best regards,
Zeng
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "SooLab/DDCOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SooLab/DDCOT] The size of tensor a (512) must match the size of tensor b (534) at non-singleton dimension 3 (Issue #4)





 
Hi ,
 Thank you for your interest in the project.
 We modified some code in the transformer library to fit our network architecture and placed our modified code in the transformer folder. Please verify the correct usage of the called functions.
 Thanks again for your collaboration.
 Best regards,
 YangBin

**Comment by YangBin55** [comment]
We train the model on 4 NVIDIA A40s with 48G for about 3 hours
